[package]
name = "todo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.19", features = ["derive"] }
diesel = { version = "2.2.4", features = ["postgres"] }
dotenv = "0.15.0"
